### ISSUE TITLE
Add incremental mode for Groups

### ISSUE THREAD

**Issue by sdorheim** [cognitedata/inso-bootstrap-cli#14]
Presently groups are always recreated when running this tool. This could be improved by doing a full compare of the objects retrieved from CDF and the configurations that is supposed to be pushed.

**Comment by spex66** [comment]
CDF Groups have no "update" API option
- they always need to be created with same or updated properties 
- and then delete the old instance
(same approach Fusion Web UI uses when you edit and save a CDF Group)

An incremental mode is impossible.

closing the issue
