### ISSUE TITLE
Possibilty to skip creation of RAW DBs

### ISSUE THREAD

**Issue by gaetan-h** [cognitedata/inso-bootstrap-cli#28]
We have an issue with the creation of RAW DBs whose names exceed the number of characters (32!) 
Would it be possible to have a flag to skip the creation of RAW DBs? 
This is not necessarily something that is used for every project, particularly if we go directly to datapoints (like DB extractor or many customer extractors running on extractor-utils)
the best would be of course to increase the number of characters in the RAW DB name, but that is out of our control

Getting the error below
cognite.client.exceptions.CogniteAPIError: dbName is too long. dbName cst2:prj:001:ship:002:rawdb:state cannot have more than 32 characters.

by setting this line to False, everything runs smoothly
https://github.com/cognitedata/inso-bootstrap-cli/blob/4d4d14992d3a84c612dff8cc973908580727802e/incubator/bootstrap_cli/__main__.py#L823

i hope it is possible to consider such a flag :) 
But i understand if you think it would make it too custom, but that would prevent us from using it and we would need to fork the repo to adapt it to our needs which we would like to avoid 👍

**Comment by spex66** [comment]
@gaetan-h pls checkout branch `new-flag-with-raw-capability`
* and test `diagram` and `deploy` with new parameter
* see PR #29 comment for examples how to use them

**Comment by spex66** [comment]
skipping some of the "templated access-control packages" (like RAW DBs) is against the idea of this approach

- supporting a workaround here (for a special case, which don't require any RAW capabilities) is mitigating the 32chars name-length limit of RAW DBs
- in parallel I started a discussion to get more "room to breath" for structured-hierarchical-namespaces (256 characters for `name` or externalId` properties of access-control related CDF configurations)
  - but as there is no ETA when this change will happen, we have this this new CLI parameter for now

**Comment by gaetan-h** [comment]
Thanks @spex66 will check it out :)

**Comment by gaetan-h** [comment]
Looks good, completed successfully now

**Comment by spex66** [comment]
closing this issue
* merged PR #29 and new feature is available in v1.10.0 now for `deploy` and `diagram` commands :)
* thx for the request and testing @gaetan-h 
* thx @sdorheim for review
