### ISSUE TITLE
No test if you ad adding a mapping to a valid CDF group

### ISSUE THREAD

**Issue by BergsethCognite** [cognitedata/inso-bootstrap-cli#35]
In the mappings section - if you add a mapping to a 'cdf-group' that don't exist bootstrap runs without any waring/errors.

Mapping is not created ( correct) - but assumed access will not be created based on AAD setup and configuration.

**Comment by BergsethCognite** [comment]
Would expect and error or warming that I try to map to a CDF group that don't exist

**Comment by spex66** [comment]
forgot to close the issue, as this validation was added in #32
