### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by BergsethCognite** [cognitedata/inso-bootstrap-cli#36]
Related to the readme I would think that how to get started should get a bit more space and higher up in the file :-)

My suggestion would be to add the "How to get started / Deployment" section - just to make it more visible...

**Comment by sdorheim** [comment]
Good point!. I will take it in to account when updating the readme for V2 of the configs!

**Comment by spex66** [comment]
hi @BergsethCognite 
Since #48 was done a while ago, we have a more consistent README.
Is it good enough for now, that we can close this issue?

**Comment by BergsethCognite** [comment]
yes - close
