### ISSUE TITLE
Whare can I find all options related to configuration

### ISSUE THREAD

**Issue by BergsethCognite** [cognitedata/inso-bootstrap-cli#37]
as for 'namespaces' used to create the dataset - the simple v2 config has some examples, but is this the full list of available options?

Looking for some hints with the command: 'poetry run bootstrap-cli --help' but can't find anything about the config file there

**Comment by BergsethCognite** [comment]
FYI . know I can look in the configuration.py file - but maybe add something to the documentation or example config file?

**Comment by spex66** [comment]
@sdorheim will help to update the documentation for v2 syntax.
We've planned to do this *after* the merge, as this allows some projects which tested the v2 changes already to migrate.

**Comment by spex66** [comment]
@BergsethCognite since PR #48 added a better readme => can we close this issue?

**Comment by spex66** [comment]
assuming now good enough :)
