### ISSUE TITLE
how to use with_special_groups?

### ISSUE THREAD

**Issue by BergsethCognite** [cognitedata/inso-bootstrap-cli#38]
Not sure what with_special_groups and how to use it - maybe add to Readme?

**Comment by spex66** [comment]
"old" CDF configs required `extractors` and `transformations` named CDF Groups for some features to work.
I've named them first "magic groups" then more professional "special groups" :)

The cli `--help` output is already available in readme:
```
➟  poetry run bootstrap-cli deploy --help
Usage: bootstrap-cli deploy [OPTIONS] [CONFIG_FILE]

  Deploy a set of bootstrap from a config-file

Options:
  --with-special-groups [yes|no]  Create special CDF Groups, which don't have
                                  capabilities (extractions, transformations).
                                  Defaults to 'no'
...
```
-----
But to my knowledge neither of them is required anymore, as transformations are supported with dedicated `transformationsAcl` capabilities, and `extractors` was allowing download of extractor (solved different now).
So maybe a good time to remove this parameter and support at all?

**Comment by spex66** [comment]
to my knowledge the "old days CDF projects" with special groups (`transformations` and `extractors`) which are using `bootstrap-cli` are 0.
I'll mark the option as deprecated for next breaking release v3
