### ISSUE TITLE
Add extractionConfigsAcl capability/acl 

### ISSUE THREAD

**Issue by lakshitha94** [cognitedata/inso-bootstrap-cli#63]
It seems like `extractionconfigs:read` and `extractionconfigs:write` capabilities are missing in bootstrap-cli. Do you have any insight on this?
https://github.com/cognitedata/inso-bootstrap-cli/blob/main/incubator/bootstrap_cli/__main__.py#L224
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/56105388/212860370-67d7dadc-d694-4a51-8ea7-dd4e7501fb20.png">

**Comment by spex66** [comment]
added and released with v2.5.1 
see https://github.com/cognitedata/inso-bootstrap-cli/releases/tag/v2.5.1
