### ISSUE TITLE
poetry.toml file forces local poetry config

### ISSUE THREAD

**Issue by petreeb** [cognitedata/inso-bootstrap-cli#72]
Poetry's documentation says:
`Your local configuration of Poetry application is stored in the poetry.toml file, which is separate from pyproject.toml.`.

`inso-boostrap-cli` shouldn't force any poetry configurations. I recommend the removal of `poetry.toml` at the top level of the repo.

**Comment by spex66** [comment]
I'll remove it from next v2 release
