### ISSUE TITLE
Being able to create extractors and transformations CDF groups from cli

### ISSUE THREAD

**Issue by CogJoel** [cognitedata/inso-bootstrap-cli#8]
A feature request here: 

We would like to be able to create the extractors and transformations CDF groups with the CLI. 

Either set it up automatically or add it as a choice within the config.

**Comment by spex66** [comment]
@CogJoel : PR #9 is on it's way

**Comment by spex66** [comment]
@CogJoel : PR #9 is merged and live in `@main` 
* a new parameter was added to the `deploy` command
=> `--with-special-groups=[yes|no]`

pls let me know if the issue can be closed

**Comment by spex66** [comment]
the release is tagged now as v1.2.1 too:
* /releases/tag/v1.2.1
* which allows tagging this exact version in gh-action workflows:
```
- uses: cognitedata/inso-bootstrap-cli@v1.2.1
```

**Comment by CogJoel** [comment]
I understand exactly where in gh-action to add 
--with-special-groups=yes

**Comment by CogJoel** [comment]
jobs:
  deploy:
    name: Deploy Bootstrap Pipelines
    environment: dev
    runs-on: ubuntu-latest
    # environment variables
    env:
      CDF_PROJECT: yourcdfproject
      CDF_CLUSTER: bluefield
      IDP_TENANT: abcde-12345
      CDF_HOST: https://bluefield.cognitedata.com/
      - name: Deploy bootstrap
        uses: cognitedata/inso-expipes-cli@main
        env:
            BOOTSTRAP_IDP_CLIENT_ID: ${{ secrets.CLIENT_ID }}
            BOOTSTRAP_IDP_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            BOOTSTRAP_CDF_HOST: ${{ env.CDF_HOST }}
            BOOTSTRAP_CDF_PROJECT: ${{ env.CDF_PROJECT }}
            BOOTSTRAP_IDP_TOKEN_URL: https://login.microsoftonline.com/${{ env.IDP_TENANT }}/oauth2/v2.0/token
            BOOTSTRAP_IDP_SCOPES: ${{ env.CDF_HOST }}.default
        # additional parameters for running the action
        with:
          config_file: ./configs/test-bootstrap-deploy-example.yml
          
Where and how I add this? --with-special-groups=yes

**Comment by spex66** [comment]
hi @CogJoel 
```yaml
        with:
          config_file: ./config/test-bootstrap-deploy-example.yml
          # deploy with special groups and aad_mappings
          with_special_groups: "yes"
```

is the way you add the new parameter to the gh-action `with` block

And that's a typo from you side?
```yaml
 uses: cognitedata/inso-expipes-cli@main
```

should be either:
```yaml
uses: cognitedata/inso-bootstrap-cli@main
```

or tagged to a release
```yaml
uses: cognitedata/inso-bootstrap-cli@v1.2.1
```

**Comment by CogJoel** [comment]
Perfect I will try that, no typo from my side I just copied the example in the readMe, feel free to change that.

**Comment by spex66** [comment]
Hi @CogJoel  
* README with the gh-action example fixed and 
* added usage of `with_special_groups` there too

**Comment by CogJoel** [comment]
Hmm Im getting an error that the action can't find the config file

config_file: ./configs/config_lyse/create.yml

Error:
FileNotFoundError: [Errno 2] No such file or directory: './configs/config_lyse/create.yml'
Incorrect file path, error message:  [Errno 2] No such file or directory: './configs/config_lyse/create.yml'

![image](https://user-images.githubusercontent.com/90243986/155286938-166aa2a6-1ec4-407b-b9fe-93de5d89ced9.png)

**Comment by CogJoel** [comment]
Works well :)! Maybe mention that you need to checkout repo content in git action section in readMe aswell.

this is how I made it run: 
jobs:
  deploy-auth-config-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main

      - name: Deploy bootstrap
        uses: cognitedata/inso-bootstrap-cli@v1.2.1
        env: 
        ....
